package Model;

import java.io.Serializable;

public class Police implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policeman.policeId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String policeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policeman.workId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policeman.name
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policeman.password
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policeman.phone
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policeman.policeId
     *
     * @return the value of policeman.policeId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getPoliceId() {
        return policeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policeman.policeId
     *
     * @param policeId the value for policeman.policeId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setPoliceId(String policeId) {
        this.policeId = policeId == null ? null : policeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policeman.workId
     *
     * @return the value of policeman.workId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policeman.workId
     *
     * @param workId the value for policeman.workId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policeman.name
     *
     * @return the value of policeman.name
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policeman.name
     *
     * @param name the value for policeman.name
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policeman.password
     *
     * @return the value of policeman.password
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policeman.password
     *
     * @param password the value for policeman.password
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policeman.phone
     *
     * @return the value of policeman.phone
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policeman.phone
     *
     * @param phone the value for policeman.phone
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}