package Model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Ticket implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticketId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.vehicleId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.city
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.violation
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String violation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.payment
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private BigDecimal payment;

    private Integer state;

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticketId
     *
     * @return the value of ticket.ticketId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getTicketId() {
        return ticketId;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticketId
     *
     * @param ticketId the value for ticket.ticketId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId == null ? null : ticketId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.vehicleId
     *
     * @return the value of ticket.vehicleId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.vehicleId
     *
     * @param vehicleId the value for ticket.vehicleId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.city
     *
     * @return the value of ticket.city
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.city
     *
     * @param city the value for ticket.city
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.violation
     *
     * @return the value of ticket.violation
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getViolation() {
        return violation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.violation
     *
     * @param violation the value for ticket.violation
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setViolation(String violation) {
        this.violation = violation == null ? null : violation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.payment
     *
     * @return the value of ticket.payment
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.payment
     *
     * @param payment the value for ticket.payment
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }
}