package Model;

import java.io.Serializable;

public class Vehicle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.userId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicleId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    private String vehicleId;

    private String key;

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.userId
     *
     * @param userId the value for vehicle.userId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicleId
     *
     * @return the value of vehicle.vehicleId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicleId
     *
     * @param vehicleId the value for vehicle.vehicleId
     *
     * @mbg.generated Sat May 25 22:07:04 CST 2019
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }
}